language: java
sudo: required
addons: 
 sonarcloud:
    organization: "radu-pisoi-github"
    token:
      secure: "${SONAR_TOKEN}"

jdk:
 - oraclejdk8
matrix:
  fast_finish: true
install: true
before_script:
  - git config credential.helper "store --file=.git/credentials"
#  - echo "https://${MY_GH_TOKEN_OXYGEN}:@github.com" > .git/credentials
#  - ./travis/checkForTag.sh
script:
  - mvn install sonar:sonar
#  - mvn cleanorg.jacoco:jacoco-maven-plugin:prepare-agent  install sonar:sonar
#before_deploy:
#  - ./travis/deploy.sh

#deploy:
#  provider: releases
#  api_key: ${MY_GH_TOKEN_OXYGEN}
#  file:
#    - target/oxygen-batch-converter-${TRAVIS_TAG}-plugin.jar
#    - target/addon.xml
#  skip_cleanup: true
#  on:
# tags: true